modLoader="javafml"
loaderVersion="[28,)"
updateJSONURL="https://raw.githubusercontent.com/gigaherz/Guidebook/master/update.json" #optional
issueTrackerURL="https://github.com/gigaherz/Guidebook/issues" #optional
displayURL="https://github.com/gigaherz/Guidebook" #optional
logoFile="logo.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="gigaherz" #optional

[[mods]] #mandatory
modId="gbook" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Guidebook" #mandatory
description='''
Books that guide
'''

[[dependencies.gbook]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28.2.3,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.gbook]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4,1.15.0)"
    ordering="NONE"
    side="BOTH"